
# cargo-vet audits file

[criteria.reviewed]
description = "you looked at it and it seems fine"
default = true
implies = []
[[audits.linked-hash-map]]
version = "0.1.0"
who = "aria"
notes = "dummy entries to check i didn't break anything"

[[audits.linked-hash-map]]
delta = "0.4.2 -> 0.5.4"
who = "aria"
notes = "dummy entries to check i didn't break anything"

[[audits.linked-hash-map]]
delta = "0.1.0 -> 0.2.0"
who = "aria"
notes = "dummy entries to check i didn't break anything"

[[audits.linked-hash-map]]
delta = "0.1.8 -> 0.2.9"
who = "aria"
notes = "dummy entries to check i didn't break anything"

[[audits.linked-hash-map]]
delta = "0.1.0 -> 0.3.0"
who = "aria"
notes = "dummy entries to check i didn't break anything"

[[audits.linked-hash-map]]
delta = "0.2.0 -> 0.4.2"
who = "aria"
notes = "dummy entries to check i didn't break anything"

[[audits.toml]]
delta = "0.5.8 -> 0.5.9"
who = "bholley"
notes = "audited for secure"

[[audits.clap_lex]]
version = "0.1.1"
who = "bholley"

[[audits.clap]]
delta = "3.1.8 -> 3.1.9"
who = "bholley"

