
# cargo-vet audits file

[criteria.reviewed]
description = "you looked at it and it seems fine"
default = true
implies = []


[[audits.linked-hash-map]]
version = "0.1.0"
notes = "dummy entries to check i didn't break anything"
who = "aria"

[[audits.linked-hash-map]]
delta = "0.4.2 -> 0.5.4"
notes = "dummy entries to check i didn't break anything"
who = "aria"

[[audits.linked-hash-map]]
delta = "0.1.0 -> 0.2.0"
notes = "dummy entries to check i didn't break anything"
who = "aria"

[[audits.linked-hash-map]]
delta = "0.1.8 -> 0.2.9"
notes = "dummy entries to check i didn't break anything"
who = "aria"

[[audits.linked-hash-map]]
delta = "0.1.0 -> 0.3.0"
notes = "dummy entries to check i didn't break anything"
who = "aria"

[[audits.linked-hash-map]]
delta = "0.2.0 -> 0.4.2"
notes = "dummy entries to check i didn't break anything"
who = "aria"