[criteria]
reviewed = "the code was reviewed"
[[audits.linked-hash-map]]
version = "0.1.2"
who = "?TODO?"
notes = "?TODO?"

[[audits.linked-hash-map]]
forbidden = "^0.1.5"
who = "?TODO?"
notes = "?TODO?"

