
# cargo-vet config file

[imports]
[[unaudited.atty]]
version = "0.2.14"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.autocfg]]
version = "1.1.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.base64]]
version = "0.13.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.bitflags]]
version = "1.3.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.bumpalo]]
version = "3.9.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.bytes]]
version = "1.1.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.camino]]
version = "1.0.7"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.cargo-platform]]
version = "0.1.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.cargo_metadata]]
version = "0.14.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.cc]]
version = "1.0.73"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.cfg-if]]
version = "1.0.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.chrono]]
version = "0.4.19"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.clap]]
version = "3.1.8"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.clap-cargo]]
version = "0.8.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.clap_derive]]
version = "3.1.7"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.console]]
version = "0.15.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.core-foundation]]
version = "0.9.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.core-foundation-sys]]
version = "0.8.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.doc-comment]]
version = "0.3.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.encode_unicode]]
version = "0.3.6"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.encoding_rs]]
version = "0.8.31"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.eyre]]
version = "0.6.8"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.fastrand]]
version = "1.7.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.fnv]]
version = "1.0.7"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.foreign-types]]
version = "0.3.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.foreign-types-shared]]
version = "0.1.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.form_urlencoded]]
version = "1.0.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.futures-channel]]
version = "0.3.21"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.futures-core]]
version = "0.3.21"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.futures-io]]
version = "0.3.21"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.futures-sink]]
version = "0.3.21"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.futures-task]]
version = "0.3.21"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.futures-util]]
version = "0.3.21"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.h2]]
version = "0.3.13"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.hashbrown]]
version = "0.11.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.heck]]
version = "0.4.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.hermit-abi]]
version = "0.1.19"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.http]]
version = "0.2.6"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.http-body]]
version = "0.4.4"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.httparse]]
version = "1.7.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.httpdate]]
version = "1.0.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.hyper]]
version = "0.14.18"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.hyper-tls]]
version = "0.5.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.idna]]
version = "0.2.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.indenter]]
version = "0.3.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.indexmap]]
version = "1.8.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.insta]]
version = "1.14.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.instant]]
version = "0.1.12"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.ipnet]]
version = "2.4.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.itoa]]
version = "1.0.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.js-sys]]
version = "0.3.57"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.lazy_static]]
version = "1.4.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.libc]]
version = "0.2.121"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.log]]
version = "0.4.16"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.matches]]
version = "0.1.9"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.memchr]]
version = "2.4.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.mime]]
version = "0.3.16"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.mio]]
version = "0.8.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.miow]]
version = "0.3.7"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.native-tls]]
version = "0.2.10"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.ntapi]]
version = "0.3.7"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.num-integer]]
version = "0.1.44"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.num-traits]]
version = "0.2.14"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.num_cpus]]
version = "1.13.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.once_cell]]
version = "1.10.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.openssl]]
version = "0.10.38"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.openssl-probe]]
version = "0.1.5"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.openssl-sys]]
version = "0.9.72"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.os_str_bytes]]
version = "6.0.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.percent-encoding]]
version = "2.1.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.pin-project-lite]]
version = "0.2.8"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.pin-utils]]
version = "0.1.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.pkg-config]]
version = "0.3.25"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.proc-macro-error]]
version = "1.0.4"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.proc-macro-error-attr]]
version = "1.0.4"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.proc-macro2]]
version = "1.0.36"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.quote]]
version = "1.0.17"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.redox_syscall]]
version = "0.2.13"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.remove_dir_all]]
version = "0.5.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.reqwest]]
version = "0.11.10"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.ryu]]
version = "1.0.9"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.schannel]]
version = "0.1.19"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.security-framework]]
version = "2.6.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.security-framework-sys]]
version = "2.6.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.semver]]
version = "1.0.7"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.serde]]
version = "1.0.136"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.serde_derive]]
version = "1.0.136"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.serde_json]]
version = "1.0.79"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.serde_test]]
version = "1.0.136"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.serde_urlencoded]]
version = "0.7.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.serde_yaml]]
version = "0.8.23"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.similar]]
version = "2.1.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.simplelog]]
version = "0.11.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.slab]]
version = "0.4.6"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.socket2]]
version = "0.4.4"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.home]]
version = "0.5.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true


[[unaudited.strsim]]
version = "0.10.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.syn]]
version = "1.0.90"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tempfile]]
version = "3.3.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.termcolor]]
version = "1.1.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.terminal_size]]
version = "0.1.17"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.textwrap]]
version = "0.15.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.time]]
version = "0.1.44"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tinyvec]]
version = "1.5.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tinyvec_macros]]
version = "0.1.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tokio]]
version = "1.17.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tokio-native-tls]]
version = "0.3.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tokio-util]]
version = "0.7.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.toml]]
version = "0.5.8"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tower-service]]
version = "0.3.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tracing]]
version = "0.1.33"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tracing-attributes]]
version = "0.1.20"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.tracing-core]]
version = "0.1.24"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.try-lock]]
version = "0.2.3"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.unicode-bidi]]
version = "0.3.7"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.unicode-normalization]]
version = "0.1.19"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.unicode-xid]]
version = "0.2.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.url]]
version = "2.2.2"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.vcpkg]]
version = "0.2.15"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.version_check]]
version = "0.9.4"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.want]]
version = "0.3.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasi]]
version = "0.10.0+wasi-snapshot-preview1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasm-bindgen]]
version = "0.2.80"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasm-bindgen-backend]]
version = "0.2.80"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasm-bindgen-futures]]
version = "0.4.30"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasm-bindgen-macro]]
version = "0.2.80"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasm-bindgen-macro-support]]
version = "0.2.80"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.wasm-bindgen-shared]]
version = "0.2.80"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.web-sys]]
version = "0.3.57"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.winapi]]
version = "0.3.9"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.winapi-util]]
version = "0.1.5"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.winreg]]
version = "0.10.1"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[[unaudited.yaml-rust]]
version = "0.4.5"
notes = "automatically imported by 'cargo vet init'"
suggest = true

[policy]

