
# cargo-vet unaudited code
#
# Helpful Comment Explaining Format                

[[atty]]
version = "0.2.14"

[[autocfg]]
version = "1.1.0"

[[bitflags]]
version = "1.3.2"

[[camino]]
version = "1.0.7"

[[cargo-platform]]
version = "0.1.2"

[[cargo_metadata]]
version = "0.14.2"

[[cfg-if]]
version = "1.0.0"

[[chrono]]
version = "0.4.19"

[[clap]]
version = "3.1.8"

[[clap-cargo]]
version = "0.8.0"

[[clap_derive]]
version = "3.1.7"

[[doc-comment]]
version = "0.3.3"

[[hashbrown]]
version = "0.11.2"

[[heck]]
version = "0.4.0"

[[hermit-abi]]
version = "0.1.19"

[[indexmap]]
version = "1.8.1"

[[itoa]]
version = "1.0.1"

[[lazy_static]]
version = "1.4.0"

[[libc]]
version = "0.2.121"

[[log]]
version = "0.4.16"

[[memchr]]
version = "2.4.1"

[[num-integer]]
version = "0.1.44"

[[num-traits]]
version = "0.2.14"

[[os_str_bytes]]
version = "6.0.0"

[[proc-macro-error]]
version = "1.0.4"

[[proc-macro-error-attr]]
version = "1.0.4"

[[proc-macro2]]
version = "1.0.36"

[[quote]]
version = "1.0.17"

[[ryu]]
version = "1.0.9"

[[semver]]
version = "1.0.7"

[[serde]]
version = "1.0.136"

[[serde_derive]]
version = "1.0.136"

[[serde_json]]
version = "1.0.79"

[[simplelog]]
version = "0.11.2"

[[strsim]]
version = "0.10.0"

[[syn]]
version = "1.0.90"

[[termcolor]]
version = "1.1.3"

[[textwrap]]
version = "0.15.0"

[[time]]
version = "0.1.44"

[[toml]]
version = "0.5.8"

[[unicode-xid]]
version = "0.2.2"

[[version_check]]
version = "0.9.4"

[[wasi]]
version = "0.10.0+wasi-snapshot-preview1"

[[winapi]]
version = "0.3.9"

[[winapi-i686-pc-windows-gnu]]
version = "0.4.0"

[[winapi-util]]
version = "0.1.5"

[[winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"

